import type {
  User,
  Branch,
  BirthYear,
  Group,
  Coach,
  Player,
  Parent,
  Session,
  AttendanceRecord,
  Evaluation,
  Measurement,
  Ranking,
  Subscription,
  Invoice,
  Notification,
  KPI,
  ChartDataPoint,
  ActivityFeedItem,
} from "@/lib/types";

// ─── Users ───────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: "u1",
    email: "admin@goalix.com",
    fullName: "Ahmed Hassan",
    role: "admin",
    phone: "+201001234567",
    avatarUrl: "",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "u2",
    email: "coach.omar@goalix.com",
    fullName: "Omar Mostafa",
    role: "coach",
    phone: "+201012345678",
    avatarUrl: "",
    createdAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "u3",
    email: "coach.kareem@goalix.com",
    fullName: "Kareem El-Sayed",
    role: "coach",
    phone: "+201023456789",
    avatarUrl: "",
    createdAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "u4",
    email: "player.youssef@goalix.com",
    fullName: "Youssef Ali",
    role: "player",
    phone: "+201034567890",
    avatarUrl: "",
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "u5",
    email: "parent.hassan@goalix.com",
    fullName: "Hassan Ibrahim",
    role: "parent",
    phone: "+201045678901",
    avatarUrl: "",
    createdAt: "2024-03-05T00:00:00Z",
  },
];

// ─── Branches ────────────────────────────────────────────────────

export const mockBranches: Branch[] = [
  {
    id: "b1",
    academyId: "a1",
    name: "Heliopolis Branch",
    address: "15 El-Nozha St, Heliopolis, Cairo",
    capacity: 200,
    currentPlayers: 156,
    coachCount: 8,
    groupCount: 12,
    status: "active",
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "b2",
    academyId: "a1",
    name: "Maadi Branch",
    address: "22 Road 9, Maadi, Cairo",
    capacity: 150,
    currentPlayers: 98,
    coachCount: 5,
    groupCount: 8,
    status: "active",
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "b3",
    academyId: "a1",
    name: "6th October Branch",
    address: "Mall of Arabia Area, 6th October City",
    capacity: 180,
    currentPlayers: 134,
    coachCount: 6,
    groupCount: 10,
    status: "active",
    createdAt: "2024-03-15T00:00:00Z",
  },
  {
    id: "b4",
    academyId: "a1",
    name: "New Cairo Branch",
    address: "5th Settlement, New Cairo",
    capacity: 120,
    currentPlayers: 45,
    coachCount: 3,
    groupCount: 4,
    status: "inactive",
    createdAt: "2024-06-01T00:00:00Z",
  },
];

// ─── Birth Years ─────────────────────────────────────────────────

export const mockBirthYears: BirthYear[] = [
  { id: "by1", branchId: "b1", label: "U12", fromYear: 2012, toYear: 2012, groupCount: 3, playerCount: 42 },
  { id: "by2", branchId: "b1", label: "U11", fromYear: 2013, toYear: 2013, groupCount: 3, playerCount: 38 },
  { id: "by3", branchId: "b1", label: "U10", fromYear: 2014, toYear: 2014, groupCount: 3, playerCount: 40 },
  { id: "by4", branchId: "b1", label: "U9", fromYear: 2015, toYear: 2015, groupCount: 3, playerCount: 36 },
  { id: "by5", branchId: "b2", label: "U12", fromYear: 2012, toYear: 2012, groupCount: 2, playerCount: 28 },
  { id: "by6", branchId: "b2", label: "U11", fromYear: 2013, toYear: 2013, groupCount: 2, playerCount: 25 },
  { id: "by7", branchId: "b2", label: "U10", fromYear: 2014, toYear: 2014, groupCount: 2, playerCount: 22 },
  { id: "by8", branchId: "b2", label: "U9", fromYear: 2015, toYear: 2015, groupCount: 2, playerCount: 23 },
  { id: "by9", branchId: "b3", label: "U12", fromYear: 2012, toYear: 2012, groupCount: 3, playerCount: 35 },
  { id: "by10", branchId: "b3", label: "U11", fromYear: 2013, toYear: 2013, groupCount: 2, playerCount: 33 },
  { id: "by11", branchId: "b3", label: "U10", fromYear: 2014, toYear: 2014, groupCount: 3, playerCount: 34 },
  { id: "by12", branchId: "b3", label: "U9", fromYear: 2015, toYear: 2015, groupCount: 2, playerCount: 32 },
];

// ─── Groups ──────────────────────────────────────────────────────

export const mockGroups: Group[] = [
  {
    id: "g1",
    branchId: "b1",
    birthYearIds: ["by1"],
    name: "Heliopolis 2012 - A",
    coachId: "c1",
    coachName: "Omar Mostafa",
    playerCount: 15,
    maxPlayers: 18,
    schedule: "Sun, Tue, Thu - 4:00 PM",
    status: "active",
  },
  {
    id: "g2",
    branchId: "b1",
    birthYearIds: ["by1"],
    name: "Heliopolis 2012 - B",
    coachId: "c2",
    coachName: "Kareem El-Sayed",
    playerCount: 14,
    maxPlayers: 18,
    schedule: "Mon, Wed, Sat - 4:00 PM",
    status: "active",
  },
  {
    id: "g3",
    branchId: "b1",
    birthYearIds: ["by2"],
    name: "Heliopolis 2013 - A",
    coachId: "c1",
    coachName: "Omar Mostafa",
    playerCount: 13,
    maxPlayers: 18,
    schedule: "Sun, Tue, Thu - 5:30 PM",
    status: "active",
  },
  {
    id: "g4",
    branchId: "b2",
    birthYearIds: ["by5"],
    name: "Maadi 2012 - A",
    coachId: "c3",
    coachName: "Tamer Adel",
    playerCount: 16,
    maxPlayers: 18,
    schedule: "Sun, Tue, Thu - 3:30 PM",
    status: "active",
  },
  {
    id: "g5",
    branchId: "b2",
    birthYearIds: ["by6"],
    name: "Maadi 2013 - A",
    coachId: "c3",
    coachName: "Tamer Adel",
    playerCount: 12,
    maxPlayers: 18,
    schedule: "Mon, Wed, Sat - 3:30 PM",
    status: "active",
  },
  {
    id: "g6",
    branchId: "b3",
    birthYearIds: ["by9"],
    name: "October 2012 - A",
    coachId: "c4",
    coachName: "Mohamed Nabil",
    playerCount: 17,
    maxPlayers: 18,
    schedule: "Sun, Tue, Thu - 4:00 PM",
    status: "active",
  },
];

// ─── Coaches ─────────────────────────────────────────────────────

export const mockCoaches: Coach[] = [
  {
    id: "c1",
    userId: "u2",
    fullName: "Omar Mostafa",
    email: "coach.omar@goalix.com",
    phone: "+201012345678",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    assignedGroups: ["g1", "g3"],
    groupNames: ["Heliopolis 2012 - A", "Heliopolis 2013 - A"],
    specialization: "Technical Skills",
    performanceScore: 92,
    status: "active",
    joinDate: "2024-02-15",
  },
  {
    id: "c2",
    userId: "u3",
    fullName: "Kareem El-Sayed",
    email: "coach.kareem@goalix.com",
    phone: "+201023456789",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    assignedGroups: ["g2"],
    groupNames: ["Heliopolis 2012 - B"],
    specialization: "Tactical Training",
    performanceScore: 87,
    status: "active",
    joinDate: "2024-02-20",
  },
  {
    id: "c3",
    userId: "u6",
    fullName: "Tamer Adel",
    email: "coach.tamer@goalix.com",
    phone: "+201056789012",
    avatarUrl: "",
    branchId: "b2",
    branchName: "Maadi Branch",
    assignedGroups: ["g4", "g5"],
    groupNames: ["Maadi 2012 - A", "Maadi 2013 - A"],
    specialization: "Physical Conditioning",
    performanceScore: 85,
    status: "active",
    joinDate: "2024-03-01",
  },
  {
    id: "c4",
    userId: "u7",
    fullName: "Mohamed Nabil",
    email: "coach.mohamed@goalix.com",
    phone: "+201067890123",
    avatarUrl: "",
    branchId: "b3",
    branchName: "6th October Branch",
    assignedGroups: ["g6"],
    groupNames: ["October 2012 - A"],
    specialization: "Goalkeeping",
    performanceScore: 90,
    status: "active",
    joinDate: "2024-03-15",
  },
  {
    id: "c5",
    userId: "u8",
    fullName: "Ali Farouk",
    email: "coach.ali@goalix.com",
    phone: "+201078901234",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    assignedGroups: [],
    groupNames: [],
    specialization: "Youth Development",
    performanceScore: 78,
    status: "inactive",
    joinDate: "2024-04-01",
  },
];

// ─── Players ─────────────────────────────────────────────────────

export const mockPlayers: Player[] = [
  {
    id: "p1",
    userId: "u4",
    fullName: "Youssef Ali",
    email: "player.youssef@goalix.com",
    phone: "+201034567890",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    groupId: "g1",
    groupName: "Heliopolis 2012 - A",
    parentId: "pa1",
    parentName: "Hassan Ibrahim",
    level: "A",
    position: "Striker",
    preferredFoot: "right",
    dateOfBirth: "2012-05-15",
    age: 12,
    height: 152,
    weight: 42,
    attendanceRate: 95,
    rankInGroup: 1,
    performanceScore: 94,
    trend: "improving",
    injuryRisk: "low",
    status: "active",
    joinDate: "2024-03-01",
  },
  {
    id: "p2",
    userId: "u9",
    fullName: "Adam Khaled",
    email: "player.adam@goalix.com",
    phone: "+201089012345",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    groupId: "g1",
    groupName: "Heliopolis 2012 - A",
    parentId: "pa2",
    parentName: "Khaled Mahmoud",
    level: "A",
    position: "Midfielder",
    preferredFoot: "left",
    dateOfBirth: "2012-08-22",
    age: 12,
    height: 148,
    weight: 40,
    attendanceRate: 90,
    rankInGroup: 2,
    performanceScore: 89,
    trend: "stable",
    injuryRisk: "low",
    status: "active",
    joinDate: "2024-03-05",
  },
  {
    id: "p3",
    userId: "u10",
    fullName: "Ziad Mohamed",
    email: "player.ziad@goalix.com",
    phone: "+201090123456",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    groupId: "g1",
    groupName: "Heliopolis 2012 - A",
    parentId: "pa3",
    parentName: "Mohamed Samir",
    level: "B",
    position: "Defender",
    preferredFoot: "right",
    dateOfBirth: "2012-02-10",
    age: 13,
    height: 155,
    weight: 45,
    attendanceRate: 82,
    rankInGroup: 5,
    performanceScore: 76,
    trend: "improving",
    injuryRisk: "medium",
    status: "active",
    joinDate: "2024-04-01",
  },
  {
    id: "p4",
    userId: "u11",
    fullName: "Omar Tarek",
    email: "player.omar@goalix.com",
    phone: "+201001122334",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    groupId: "g2",
    groupName: "Heliopolis 2012 - B",
    parentId: "pa4",
    parentName: "Tarek Youssef",
    level: "B",
    position: "Goalkeeper",
    preferredFoot: "right",
    dateOfBirth: "2012-11-03",
    age: 12,
    height: 158,
    weight: 48,
    attendanceRate: 88,
    rankInGroup: 3,
    performanceScore: 81,
    trend: "stable",
    injuryRisk: "low",
    status: "active",
    joinDate: "2024-03-10",
  },
  {
    id: "p5",
    userId: "u12",
    fullName: "Seif Amr",
    email: "player.seif@goalix.com",
    phone: "+201002233445",
    avatarUrl: "",
    branchId: "b2",
    branchName: "Maadi Branch",
    groupId: "g4",
    groupName: "Maadi 2012 - A",
    parentId: "pa5",
    parentName: "Amr Hussein",
    level: "A",
    position: "Winger",
    preferredFoot: "both",
    dateOfBirth: "2012-07-18",
    age: 12,
    height: 150,
    weight: 41,
    attendanceRate: 93,
    rankInGroup: 1,
    performanceScore: 91,
    trend: "improving",
    injuryRisk: "low",
    status: "active",
    joinDate: "2024-03-20",
  },
  {
    id: "p6",
    userId: "u13",
    fullName: "Karim Hesham",
    email: "player.karim@goalix.com",
    phone: "+201003344556",
    avatarUrl: "",
    branchId: "b2",
    branchName: "Maadi Branch",
    groupId: "g4",
    groupName: "Maadi 2012 - A",
    parentId: "pa6",
    parentName: "Hesham Fathy",
    level: "C",
    position: "Midfielder",
    preferredFoot: "right",
    dateOfBirth: "2012-01-25",
    age: 13,
    height: 145,
    weight: 39,
    attendanceRate: 70,
    rankInGroup: 12,
    performanceScore: 58,
    trend: "declining",
    injuryRisk: "low",
    status: "active",
    joinDate: "2024-05-01",
  },
  {
    id: "p7",
    userId: "u14",
    fullName: "Mazen Walid",
    email: "player.mazen@goalix.com",
    phone: "+201004455667",
    avatarUrl: "",
    branchId: "b3",
    branchName: "6th October Branch",
    groupId: "g6",
    groupName: "October 2012 - A",
    parentId: "pa7",
    parentName: "Walid Ashraf",
    level: "A",
    position: "Striker",
    preferredFoot: "left",
    dateOfBirth: "2012-09-30",
    age: 12,
    height: 154,
    weight: 44,
    attendanceRate: 97,
    rankInGroup: 1,
    performanceScore: 96,
    trend: "improving",
    injuryRisk: "low",
    status: "active",
    joinDate: "2024-03-15",
  },
  {
    id: "p8",
    userId: "u15",
    fullName: "Khaled Sherif",
    email: "player.khaled@goalix.com",
    phone: "+201005566778",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    groupId: "g3",
    groupName: "Heliopolis 2013 - A",
    parentId: "pa8",
    parentName: "Sherif Nour",
    level: "B",
    position: "Defender",
    preferredFoot: "right",
    dateOfBirth: "2013-04-12",
    age: 12,
    height: 143,
    weight: 37,
    attendanceRate: 85,
    rankInGroup: 4,
    performanceScore: 74,
    trend: "stable",
    injuryRisk: "medium",
    status: "active",
    joinDate: "2024-04-15",
  },
  {
    id: "p9",
    userId: "u16",
    fullName: "Taha Ibrahim",
    email: "player.taha@goalix.com",
    phone: "+201006677889",
    avatarUrl: "",
    branchId: "b1",
    branchName: "Heliopolis Branch",
    groupId: "g1",
    groupName: "Heliopolis 2012 - A",
    parentId: "pa9",
    parentName: "Ibrahim Farid",
    level: "A",
    position: "Midfielder",
    preferredFoot: "right",
    dateOfBirth: "2012-12-05",
    age: 12,
    height: 149,
    weight: 41,
    attendanceRate: 91,
    rankInGroup: 3,
    performanceScore: 88,
    trend: "improving",
    injuryRisk: "low",
    status: "active",
    joinDate: "2024-03-01",
  },
  {
    id: "p10",
    userId: "u17",
    fullName: "Nour Magdy",
    email: "player.nour@goalix.com",
    phone: "+201007788990",
    avatarUrl: "",
    branchId: "b3",
    branchName: "6th October Branch",
    groupId: "g6",
    groupName: "October 2012 - A",
    parentId: "pa10",
    parentName: "Magdy Sayed",
    level: "B",
    position: "Winger",
    preferredFoot: "left",
    dateOfBirth: "2012-06-22",
    age: 12,
    height: 147,
    weight: 39,
    attendanceRate: 78,
    rankInGroup: 8,
    performanceScore: 72,
    trend: "declining",
    injuryRisk: "high",
    status: "injured",
    joinDate: "2024-04-01",
  },
];

// ─── Parents ─────────────────────────────────────────────────────

export const mockParents: Parent[] = [
  {
    id: "pa1",
    userId: "u5",
    fullName: "Hassan Ibrahim",
    email: "parent.hassan@goalix.com",
    phone: "+201045678901",
    avatarUrl: "",
    childrenIds: ["p1"],
    childrenNames: ["Youssef Ali"],
  },
  {
    id: "pa2",
    userId: "u18",
    fullName: "Khaled Mahmoud",
    email: "parent.khaled@goalix.com",
    phone: "+201056789012",
    avatarUrl: "",
    childrenIds: ["p2"],
    childrenNames: ["Adam Khaled"],
  },
  {
    id: "pa3",
    userId: "u19",
    fullName: "Mohamed Samir",
    email: "parent.mohamed@goalix.com",
    phone: "+201067890123",
    avatarUrl: "",
    childrenIds: ["p3"],
    childrenNames: ["Ziad Mohamed"],
  },
  {
    id: "pa4",
    userId: "u20",
    fullName: "Tarek Youssef",
    email: "parent.tarek@goalix.com",
    phone: "+201078901234",
    avatarUrl: "",
    childrenIds: ["p4"],
    childrenNames: ["Omar Tarek"],
  },
  {
    id: "pa5",
    userId: "u21",
    fullName: "Amr Hussein",
    email: "parent.amr@goalix.com",
    phone: "+201089012345",
    avatarUrl: "",
    childrenIds: ["p5"],
    childrenNames: ["Seif Amr"],
  },
];

// ─── Sessions ────────────────────────────────────────────────────

export const mockSessions: Session[] = [
  {
    id: "s1",
    groupId: "g1",
    groupName: "Heliopolis 2012 - A",
    coachId: "c1",
    coachName: "Omar Mostafa",
    date: "2025-01-12",
    startTime: "16:00",
    endTime: "17:30",
    type: "training",
    notes: "Focus on passing drills and ball control",
    attendanceCount: 14,
    totalPlayers: 15,
  },
  {
    id: "s2",
    groupId: "g1",
    groupName: "Heliopolis 2012 - A",
    coachId: "c1",
    coachName: "Omar Mostafa",
    date: "2025-01-14",
    startTime: "16:00",
    endTime: "17:30",
    type: "training",
    notes: "Defensive positioning and set pieces",
    attendanceCount: 13,
    totalPlayers: 15,
  },
  {
    id: "s3",
    groupId: "g2",
    groupName: "Heliopolis 2012 - B",
    coachId: "c2",
    coachName: "Kareem El-Sayed",
    date: "2025-01-13",
    startTime: "16:00",
    endTime: "17:30",
    type: "training",
    notes: "Sprint drills and agility training",
    attendanceCount: 12,
    totalPlayers: 14,
  },
  {
    id: "s4",
    groupId: "g4",
    groupName: "Maadi 2012 - A",
    coachId: "c3",
    coachName: "Tamer Adel",
    date: "2025-01-12",
    startTime: "15:30",
    endTime: "17:00",
    type: "match",
    notes: "Friendly match vs Al-Ahly Academy youth",
    attendanceCount: 16,
    totalPlayers: 16,
  },
  {
    id: "s5",
    groupId: "g6",
    groupName: "October 2012 - A",
    coachId: "c4",
    coachName: "Mohamed Nabil",
    date: "2025-01-12",
    startTime: "16:00",
    endTime: "17:30",
    type: "assessment",
    notes: "Monthly assessment – technical and physical tests",
    attendanceCount: 17,
    totalPlayers: 17,
  },
  {
    id: "s6",
    groupId: "g1",
    groupName: "Heliopolis 2012 - A",
    coachId: "c1",
    coachName: "Omar Mostafa",
    date: "2025-01-16",
    startTime: "16:00",
    endTime: "17:30",
    type: "training",
    notes: "Shooting practice and finishing",
    attendanceCount: 15,
    totalPlayers: 15,
  },
];

// ─── Attendance Records ──────────────────────────────────────────

export const mockAttendanceRecords: AttendanceRecord[] = [
  { id: "att1", sessionId: "s1", playerId: "p1", playerName: "Youssef Ali", status: "present", markedBy: "c1", markedAt: "2025-01-12T16:05:00Z" },
  { id: "att2", sessionId: "s1", playerId: "p2", playerName: "Adam Khaled", status: "present", markedBy: "c1", markedAt: "2025-01-12T16:05:00Z" },
  { id: "att3", sessionId: "s1", playerId: "p3", playerName: "Ziad Mohamed", status: "late", notes: "Arrived 15 min late", markedBy: "c1", markedAt: "2025-01-12T16:15:00Z" },
  { id: "att4", sessionId: "s1", playerId: "p9", playerName: "Taha Ibrahim", status: "present", markedBy: "c1", markedAt: "2025-01-12T16:05:00Z" },
  { id: "att5", sessionId: "s2", playerId: "p1", playerName: "Youssef Ali", status: "present", markedBy: "c1", markedAt: "2025-01-14T16:05:00Z" },
  { id: "att6", sessionId: "s2", playerId: "p2", playerName: "Adam Khaled", status: "absent", notes: "Sick – parent notified", markedBy: "c1", markedAt: "2025-01-14T16:05:00Z" },
  { id: "att7", sessionId: "s2", playerId: "p3", playerName: "Ziad Mohamed", status: "present", markedBy: "c1", markedAt: "2025-01-14T16:05:00Z" },
  { id: "att8", sessionId: "s2", playerId: "p9", playerName: "Taha Ibrahim", status: "excused", notes: "School exam", markedBy: "c1", markedAt: "2025-01-14T16:05:00Z" },
  { id: "att9", sessionId: "s3", playerId: "p4", playerName: "Omar Tarek", status: "present", markedBy: "c2", markedAt: "2025-01-13T16:05:00Z" },
  { id: "att10", sessionId: "s4", playerId: "p5", playerName: "Seif Amr", status: "present", markedBy: "c3", markedAt: "2025-01-12T15:35:00Z" },
  { id: "att11", sessionId: "s4", playerId: "p6", playerName: "Karim Hesham", status: "absent", markedBy: "c3", markedAt: "2025-01-12T15:35:00Z" },
  { id: "att12", sessionId: "s5", playerId: "p7", playerName: "Mazen Walid", status: "present", markedBy: "c4", markedAt: "2025-01-12T16:05:00Z" },
  { id: "att13", sessionId: "s5", playerId: "p10", playerName: "Nour Magdy", status: "absent", notes: "Injury recovery", markedBy: "c4", markedAt: "2025-01-12T16:05:00Z" },
];

// ─── Evaluations ─────────────────────────────────────────────────

export const mockEvaluations: Evaluation[] = [
  {
    id: "ev1",
    playerId: "p1",
    playerName: "Youssef Ali",
    coachId: "c1",
    coachName: "Omar Mostafa",
    date: "2025-01-10",
    technicalScore: 9.2,
    tacticalScore: 8.5,
    physicalScore: 8.8,
    mentalScore: 9.0,
    overallScore: 8.9,
    notes: "Exceptional ball control and vision. Needs to improve defensive awareness.",
  },
  {
    id: "ev2",
    playerId: "p2",
    playerName: "Adam Khaled",
    coachId: "c1",
    coachName: "Omar Mostafa",
    date: "2025-01-10",
    technicalScore: 8.5,
    tacticalScore: 8.8,
    physicalScore: 8.0,
    mentalScore: 8.5,
    overallScore: 8.5,
    notes: "Great tactical understanding for his age. Left foot is a real asset.",
  },
  {
    id: "ev3",
    playerId: "p3",
    playerName: "Ziad Mohamed",
    coachId: "c1",
    coachName: "Omar Mostafa",
    date: "2025-01-10",
    technicalScore: 7.0,
    tacticalScore: 7.5,
    physicalScore: 8.2,
    mentalScore: 6.8,
    overallScore: 7.4,
    notes: "Physically strong but needs to work on discipline and focus during sessions.",
  },
  {
    id: "ev4",
    playerId: "p5",
    playerName: "Seif Amr",
    coachId: "c3",
    coachName: "Tamer Adel",
    date: "2025-01-11",
    technicalScore: 9.0,
    tacticalScore: 8.0,
    physicalScore: 9.2,
    mentalScore: 8.5,
    overallScore: 8.7,
    notes: "Fastest player in the group. Excellent dribbling and acceleration.",
  },
  {
    id: "ev5",
    playerId: "p7",
    playerName: "Mazen Walid",
    coachId: "c4",
    coachName: "Mohamed Nabil",
    date: "2025-01-12",
    technicalScore: 9.5,
    tacticalScore: 9.0,
    physicalScore: 9.0,
    mentalScore: 9.5,
    overallScore: 9.3,
    notes: "Outstanding talent. Leadership qualities on the field. Potential for elite pathway.",
  },
  {
    id: "ev6",
    playerId: "p6",
    playerName: "Karim Hesham",
    coachId: "c3",
    coachName: "Tamer Adel",
    date: "2025-01-11",
    technicalScore: 5.5,
    tacticalScore: 5.0,
    physicalScore: 6.0,
    mentalScore: 5.2,
    overallScore: 5.4,
    notes: "Struggling with motivation. Frequent absences affecting progress. Parent meeting recommended.",
  },
];

// ─── Measurements ────────────────────────────────────────────────

export const mockMeasurements: Measurement[] = [
  { id: "m1", playerId: "p1", playerName: "Youssef Ali", date: "2024-10-01", height: 148, weight: 39, sprintSpeed: 7.2, endurance: 8.0, flexibility: 7.5, recordedBy: "c1" },
  { id: "m2", playerId: "p1", playerName: "Youssef Ali", date: "2024-12-01", height: 150, weight: 40, sprintSpeed: 7.0, endurance: 8.2, flexibility: 7.8, recordedBy: "c1" },
  { id: "m3", playerId: "p1", playerName: "Youssef Ali", date: "2025-01-10", height: 152, weight: 42, sprintSpeed: 6.8, endurance: 8.5, flexibility: 8.0, recordedBy: "c1" },
  { id: "m4", playerId: "p2", playerName: "Adam Khaled", date: "2024-10-01", height: 145, weight: 37, sprintSpeed: 7.5, endurance: 7.8, flexibility: 8.2, recordedBy: "c1" },
  { id: "m5", playerId: "p2", playerName: "Adam Khaled", date: "2025-01-10", height: 148, weight: 40, sprintSpeed: 7.2, endurance: 8.0, flexibility: 8.5, recordedBy: "c1" },
  { id: "m6", playerId: "p5", playerName: "Seif Amr", date: "2025-01-11", height: 150, weight: 41, sprintSpeed: 6.5, endurance: 8.8, flexibility: 7.0, recordedBy: "c3" },
  { id: "m7", playerId: "p7", playerName: "Mazen Walid", date: "2025-01-12", height: 154, weight: 44, sprintSpeed: 6.6, endurance: 9.0, flexibility: 7.5, recordedBy: "c4" },
];

// ─── Rankings ────────────────────────────────────────────────────

export const mockRankings: Ranking[] = [
  { id: "r1", playerId: "p1", playerName: "Youssef Ali", groupId: "g1", groupName: "Heliopolis 2012 - A", rank: 1, previousRank: 1, score: 94, trend: "improving", period: "weekly", date: "2025-01-12" },
  { id: "r2", playerId: "p2", playerName: "Adam Khaled", groupId: "g1", groupName: "Heliopolis 2012 - A", rank: 2, previousRank: 3, score: 89, trend: "improving", period: "weekly", date: "2025-01-12" },
  { id: "r3", playerId: "p9", playerName: "Taha Ibrahim", groupId: "g1", groupName: "Heliopolis 2012 - A", rank: 3, previousRank: 2, score: 88, trend: "declining", period: "weekly", date: "2025-01-12" },
  { id: "r4", playerId: "p3", playerName: "Ziad Mohamed", groupId: "g1", groupName: "Heliopolis 2012 - A", rank: 5, previousRank: 7, score: 76, trend: "improving", period: "weekly", date: "2025-01-12" },
  { id: "r5", playerId: "p4", playerName: "Omar Tarek", groupId: "g2", groupName: "Heliopolis 2012 - B", rank: 3, previousRank: 3, score: 81, trend: "stable", period: "weekly", date: "2025-01-12" },
  { id: "r6", playerId: "p5", playerName: "Seif Amr", groupId: "g4", groupName: "Maadi 2012 - A", rank: 1, previousRank: 2, score: 91, trend: "improving", period: "weekly", date: "2025-01-12" },
  { id: "r7", playerId: "p6", playerName: "Karim Hesham", groupId: "g4", groupName: "Maadi 2012 - A", rank: 12, previousRank: 10, score: 58, trend: "declining", period: "weekly", date: "2025-01-12" },
  { id: "r8", playerId: "p7", playerName: "Mazen Walid", groupId: "g6", groupName: "October 2012 - A", rank: 1, previousRank: 1, score: 96, trend: "improving", period: "weekly", date: "2025-01-12" },
  { id: "r9", playerId: "p10", playerName: "Nour Magdy", groupId: "g6", groupName: "October 2012 - A", rank: 8, previousRank: 5, score: 72, trend: "declining", period: "weekly", date: "2025-01-12" },
];

// ─── Subscriptions ───────────────────────────────────────────────

export const mockSubscriptions: Subscription[] = [
  { id: "sub1", playerId: "p1", playerName: "Youssef Ali", parentId: "pa1", parentName: "Hassan Ibrahim", plan: "quarterly", amount: 2400, status: "paid", startDate: "2025-01-01", endDate: "2025-03-31", renewalDate: "2025-03-25" },
  { id: "sub2", playerId: "p2", playerName: "Adam Khaled", parentId: "pa2", parentName: "Khaled Mahmoud", plan: "monthly", amount: 900, status: "paid", startDate: "2025-01-01", endDate: "2025-01-31", renewalDate: "2025-01-25" },
  { id: "sub3", playerId: "p3", playerName: "Ziad Mohamed", parentId: "pa3", parentName: "Mohamed Samir", plan: "monthly", amount: 900, status: "overdue", startDate: "2024-12-01", endDate: "2024-12-31", renewalDate: "2024-12-25" },
  { id: "sub4", playerId: "p4", playerName: "Omar Tarek", parentId: "pa4", parentName: "Tarek Youssef", plan: "yearly", amount: 8400, status: "paid", startDate: "2024-09-01", endDate: "2025-08-31", renewalDate: "2025-08-25" },
  { id: "sub5", playerId: "p5", playerName: "Seif Amr", parentId: "pa5", parentName: "Amr Hussein", plan: "quarterly", amount: 2400, status: "pending", startDate: "2025-01-01", endDate: "2025-03-31", renewalDate: "2025-03-25" },
  { id: "sub6", playerId: "p6", playerName: "Karim Hesham", parentId: "pa6", parentName: "Hesham Fathy", plan: "monthly", amount: 900, status: "overdue", startDate: "2024-11-01", endDate: "2024-11-30", renewalDate: "2024-11-25" },
  { id: "sub7", playerId: "p7", playerName: "Mazen Walid", parentId: "pa7", parentName: "Walid Ashraf", plan: "yearly", amount: 8400, status: "paid", startDate: "2024-06-01", endDate: "2025-05-31", renewalDate: "2025-05-25" },
];

// ─── Invoices ────────────────────────────────────────────────────

export const mockInvoices: Invoice[] = [
  { id: "inv1", subscriptionId: "sub1", playerId: "p1", playerName: "Youssef Ali", parentId: "pa1", parentName: "Hassan Ibrahim", amount: 2400, status: "paid", issueDate: "2025-01-01", dueDate: "2025-01-10", paidDate: "2025-01-05" },
  { id: "inv2", subscriptionId: "sub2", playerId: "p2", playerName: "Adam Khaled", parentId: "pa2", parentName: "Khaled Mahmoud", amount: 900, status: "paid", issueDate: "2025-01-01", dueDate: "2025-01-10", paidDate: "2025-01-08" },
  { id: "inv3", subscriptionId: "sub3", playerId: "p3", playerName: "Ziad Mohamed", parentId: "pa3", parentName: "Mohamed Samir", amount: 900, status: "overdue", issueDate: "2024-12-01", dueDate: "2024-12-10" },
  { id: "inv4", subscriptionId: "sub5", playerId: "p5", playerName: "Seif Amr", parentId: "pa5", parentName: "Amr Hussein", amount: 2400, status: "pending", issueDate: "2025-01-01", dueDate: "2025-01-15" },
  { id: "inv5", subscriptionId: "sub6", playerId: "p6", playerName: "Karim Hesham", parentId: "pa6", parentName: "Hesham Fathy", amount: 900, status: "overdue", issueDate: "2024-11-01", dueDate: "2024-11-10" },
];

// ─── Notifications ───────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  { id: "n1", title: "Payment Overdue", message: "Ziad Mohamed's subscription payment is overdue by 12 days.", type: "warning", channel: "in_app", targetRole: "admin", read: false, sentAt: "2025-01-12T09:00:00Z", sentBy: "system" },
  { id: "n2", title: "New Player Registered", message: "A new player Nader Ashraf has been registered at Heliopolis Branch.", type: "info", channel: "in_app", targetRole: "admin", read: false, sentAt: "2025-01-11T14:30:00Z", sentBy: "system" },
  { id: "n3", title: "Attendance Alert", message: "Karim Hesham has missed 3 consecutive sessions in Maadi 2012 - A.", type: "alert", channel: "in_app", targetRole: "admin", read: true, sentAt: "2025-01-10T18:00:00Z", sentBy: "system" },
  { id: "n4", title: "Evaluation Submitted", message: "Coach Omar Mostafa submitted evaluations for 15 players in Heliopolis 2012 - A.", type: "success", channel: "in_app", targetRole: "admin", read: true, sentAt: "2025-01-10T17:00:00Z", sentBy: "c1" },
  { id: "n5", title: "Injury Report", message: "Nour Magdy (October 2012 - A) reported an ankle sprain. Expected recovery: 2 weeks.", type: "alert", channel: "in_app", targetRole: "admin", read: false, sentAt: "2025-01-09T11:00:00Z", sentBy: "c4" },
  { id: "n6", title: "Monthly Report Ready", message: "December 2024 performance reports are ready for review.", type: "info", channel: "in_app", targetRole: "admin", read: true, sentAt: "2025-01-05T08:00:00Z", sentBy: "system" },
  { id: "n7", title: "Training Cancelled", message: "Tomorrow's session for Maadi 2012 - A has been cancelled due to weather.", type: "warning", channel: "in_app", targetRole: "coach", targetIds: ["c3"], read: false, sentAt: "2025-01-13T20:00:00Z", sentBy: "admin" },
  { id: "n8", title: "Great Progress!", message: "Your ranking improved from #3 to #1 this week. Keep it up!", type: "success", channel: "in_app", targetRole: "player", targetIds: ["p5"], read: false, sentAt: "2025-01-12T10:00:00Z", sentBy: "system" },
];

// ─── Dashboard KPIs ──────────────────────────────────────────────

export const mockAdminKPIs: KPI[] = [
  { label: "Total Players", value: 433, change: 12, changeLabel: "vs last month", icon: "Users" },
  { label: "Attendance Rate", value: "87%", change: 3.2, changeLabel: "vs last week", icon: "ClipboardCheck" },
  { label: "Monthly Revenue", value: "EGP 156,200", change: 8.5, changeLabel: "vs last month", icon: "CreditCard" },
  { label: "Active Coaches", value: 19, change: 2, changeLabel: "new this month", icon: "UserCheck" },
  { label: "Active Groups", value: 30, change: 0, changeLabel: "no change", icon: "Layers" },
  { label: "Overdue Payments", value: 23, change: -5, changeLabel: "vs last month", icon: "AlertTriangle" },
];

// ─── Chart Data ──────────────────────────────────────────────────

export const mockAttendanceChartData: ChartDataPoint[] = [
  { label: "Week 1", value: 85 },
  { label: "Week 2", value: 88 },
  { label: "Week 3", value: 82 },
  { label: "Week 4", value: 90 },
  { label: "Week 5", value: 87 },
  { label: "Week 6", value: 91 },
  { label: "Week 7", value: 89 },
  { label: "Week 8", value: 93 },
];

export const mockRevenueChartData: ChartDataPoint[] = [
  { label: "Aug", value: 120000 },
  { label: "Sep", value: 135000 },
  { label: "Oct", value: 142000 },
  { label: "Nov", value: 138000 },
  { label: "Dec", value: 150000 },
  { label: "Jan", value: 156200 },
];

// ─── Activity Feed ───────────────────────────────────────────────

export const mockActivityFeed: ActivityFeedItem[] = [
  { id: "af1", type: "attendance", message: "Coach Omar marked attendance for Heliopolis 2012 - A (14/15 present)", timestamp: "2025-01-12T16:05:00Z", userId: "c1", userName: "Omar Mostafa" },
  { id: "af2", type: "evaluation", message: "5 new evaluations submitted for Heliopolis 2012 - A", timestamp: "2025-01-10T17:00:00Z", userId: "c1", userName: "Omar Mostafa" },
  { id: "af3", type: "payment", message: "Payment of EGP 2,400 received from Hassan Ibrahim (Youssef Ali)", timestamp: "2025-01-05T10:30:00Z", userId: "pa1", userName: "Hassan Ibrahim" },
  { id: "af4", type: "player", message: "New player Nader Ashraf registered at Heliopolis Branch", timestamp: "2025-01-11T14:30:00Z" },
  { id: "af5", type: "notification", message: "Injury report filed for Nour Magdy – ankle sprain", timestamp: "2025-01-09T11:00:00Z", userId: "c4", userName: "Mohamed Nabil" },
  { id: "af6", type: "attendance", message: "Coach Tamer marked attendance for Maadi 2012 - A (15/16 present)", timestamp: "2025-01-12T15:35:00Z", userId: "c3", userName: "Tamer Adel" },
  { id: "af7", type: "payment", message: "Payment overdue alert: Ziad Mohamed – EGP 900 (12 days)", timestamp: "2025-01-12T09:00:00Z" },
  { id: "af8", type: "evaluation", message: "Monthly assessment completed for October 2012 - A", timestamp: "2025-01-12T17:30:00Z", userId: "c4", userName: "Mohamed Nabil" },
];
